<a href="https://colab.research.google.com/github/saimahesh16/adv-pprog/blob/master/Day_11(5_06_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from numpy import random
print(random.randint(1,29))
print(random.rand())

24
0.2680538077159209


In [0]:
random.randint(100,size=3)

array([84,  7, 13])

In [0]:
random.randint(100,size=3)

array([93, 53, 50])

In [0]:
random.randint(100,size=(3,4))

array([[30, 45, 94, 38],
       [55, 89, 51, 86],
       [93,  0, 81, 82]])

In [0]:
random.randint(100,size=(3,4,2))

array([[[57, 26],
        [ 9, 93],
        [95, 38],
        [76, 62]],

       [[53, 48],
        [45, 21],
        [82, 79],
        [28, 78]],

       [[66, 44],
        [73, 52],
        [30, 15],
        [93, 59]]])

In [0]:
random.rand()

0.1139012222338559

In [0]:
random.rand(2)

array([0.82833369, 0.18582635])

In [0]:
random.rand(2,3)

array([[0.5856274 , 0.70570246, 0.76563755],
       [0.43494018, 0.74265319, 0.53118749]])

In [0]:
a=random.randint(100,size=(4))
a

array([72, 25, 79, 65])

In [0]:
random.choice(a)

72

In [0]:
random.choice([1,2,3,4,5],size=(3,4))

array([[4, 2, 2, 3],
       [3, 4, 5, 2],
       [3, 5, 5, 2]])

In [0]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [0]:
d1={"name":["mahesh","mahi","jagu"],"address":["hyd","usa","AP"]}
df1=pd.DataFrame(d1)
df1

name address
0  mahesh     hyd
1    mahi     usa
2    jagu      AP

In [0]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([11.22,33.32,22.2,44.4,55.5,66.6,77.77,88.88,99.9,65])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"colum1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

colum1  column2 column3
0       1    11.22       a
1       2    33.32       b
2       3    22.20       c
3       4    44.40       d
4       5    55.50       e
5       6    66.60       f
6       7    77.77       g
7       8    88.88       h
8       9    99.90       i
9      10    65.00       j

In [0]:
df3["column2"]

0    11.22
1    33.32
2    22.20
3    44.40
4    55.50
5    66.60
6    77.77
7    88.88
8    99.90
9    65.00
Name: column2, dtype: float64

In [0]:
df3.loc[:"column1"]

colum1  column2 column3
0       1    11.22       a
1       2    33.32       b
2       3    22.20       c
3       4    44.40       d
4       5    55.50       e
5       6    66.60       f
6       7    77.77       g
7       8    88.88       h
8       9    99.90       i
9      10    65.00       j

In [0]:
df3[["column2","column3"]]

column2 column3
0    11.22       a
1    33.32       b
2    22.20       c
3    44.40       d
4    55.50       e
5    66.60       f
6    77.77       g
7    88.88       h
8    99.90       i
9    65.00       j

In [0]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: colum1, dtype: int64

In [0]:
df3.iloc[0:4,0:1]

colum1
0       1
1       2
2       3
3       4

In [0]:
df3.shape

(10, 3)

In [0]:
df3.columns

Index(['colum1', 'column2', 'column3'], dtype='object')

In [0]:
df3.index

RangeIndex(start=0, stop=10, step=1)

In [0]:
df3.head()

colum1  column2 column3
0       1    11.22       a
1       2    33.32       b
2       3    22.20       c
3       4    44.40       d
4       5    55.50       e

In [0]:
df3.head(3)

colum1  column2 column3
0       1    11.22       a
1       2    33.32       b
2       3    22.20       c

In [0]:
df3.tail()

colum1  column2 column3
5       6    66.60       f
6       7    77.77       g
7       8    88.88       h
8       9    99.90       i
9      10    65.00       j

In [0]:
df3.tail(2)

colum1  column2 column3
8       9     99.9       i
9      10     65.0       j

In [0]:
df3.sample()

colum1  column2 column3
8       9     99.9       i

In [0]:
df3.sample(2)

colum1  column2 column3
7       8    88.88       h
9      10    65.00       j

In [0]:
df3.describe()

colum1    column2
count  10.00000  10.000000
mean    5.50000  56.479000
std     3.02765  28.810075
min     1.00000  11.220000
25%     3.25000  36.090000
50%     5.50000  60.250000
75%     7.75000  74.977500
max    10.00000  99.900000