<a href="https://colab.research.google.com/github/saimahesh16/adv-pprog/blob/master/Day_10_(4_06_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a1=np.array([[1,2,3],[3,4,5],[5,6,7]])
a1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [0]:
a1.ndim

2

In [0]:
a1.shape

(3, 3)

In [0]:
a2=np.arange(1,10)
a3=np.array([[1,2,3],[3,4,6]])
print(a2,a3)

[1 2 3 4 5 6 7 8 9] [[1 2 3]
 [3 4 6]]


In [0]:
a3=np.append(a3,int(input()))

15


In [0]:
a3

array([ 1,  2,  3,  3,  4,  6, 15])

In [0]:
a3=np.append(a3,[1,2,3,4,5])

In [0]:
a3

array([ 1,  2,  3,  3,  4,  6, 15,  1,  2,  3,  4,  5])

In [0]:
a3.ndim

1

In [0]:
a3[5]

6

In [0]:
a3[1:4]

array([2, 3, 3])

In [0]:
a3=np.array([[1,2,3],[3,4,6]])
a3[0:2,1:]

array([[2, 3],
       [4, 6]])

In [0]:
a3[:,:]

array([[1, 2, 3],
       [3, 4, 6]])

In [0]:
a4=np.arange(1,21).reshape(5,4)

In [0]:
a4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [0]:
result= (a4%2==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [0]:
a4[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
for row in a3:
    print(row)
for i in a3.flat:
    print(i,end=" ")

[1 2 3]
[3 4 6]
1 2 3 3 4 6 

In [0]:
ar1=np.arange(1,10).reshape(3,3)
ar2=np.arange(11,20).reshape(3,3)
print(np.hstack((ar1,ar2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [0]:
print(ar1.size)
print(ar1.itemsize)
print(ar1.dtype)
print(ar1.ndim)
print(ar1.shape)

9
4
int32
2
(3, 3)


In [0]:
ar1=np.arange(1,10).reshape(3,3)
ar2=np.arange(11,20).reshape(3,3)
print(np.vstack((ar1,ar2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [0]:
z=np.zeros((2,3),dtype='int32')
z

array([[0, 0, 0],
       [0, 0, 0]])

In [0]:
z=np.ones((2,3),dtype='int32')
z

array([[1, 1, 1],
       [1, 1, 1]])

In [0]:
z=np.full((2,3),"kbc")
z

array([['kbc', 'kbc', 'kbc'],
       ['kbc', 'kbc', 'kbc']], dtype='<U3')

In [0]:
n=np.eye(3,dtype='int32')
n

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [0]:
n1=np.linspace(1,10,5)
n1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [0]:
np.ravel(n)

array([1, 0, 0, 0, 1, 0, 0, 0, 1])

In [0]:
a4.min()

1

In [0]:
a4.max()

20

In [0]:
a4.sum()

210

In [0]:
a4.sum(axis=0)#column

array([45, 50, 55, 60])

In [0]:
a4.sum(axis=1)#row

array([10, 26, 42, 58, 74])

In [0]:
print(np.sqrt(a4),np.mean(a4),np.median(a4))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]
 [4.12310563 4.24264069 4.35889894 4.47213595]] 10.5 10.5


In [0]:
ar1+ar2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [0]:
ar1/ar2

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [0]:
ar1%ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [0]:
ar1<=ar2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [0]:
np.dot(ar1,ar2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [0]:
ar1.dot(ar2) #multiplication

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [0]:
ar1.T #transpose of an array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [0]:
l1=list(range(1,20))
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [0]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [0]:
result=[x/(x+1) for x in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [0]:
f=np.vectorize(lambda x:x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [0]:
a/(a+1)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])